### ISSUE TITLE
main panic, trying to compile examples

### ISSUE THREAD

**Issue by mrlogick** [bluez/bluer#128]
```
$ git checkout master
$ RUST_BACKTRACE=1 cargo run --example discover_devices

error: failed to run custom build command for `bluer v0.17.0 (/home/mrlogick/Desktop/bluer/bluer)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/home/mrlogick/Desktop/bluer/target/debug/build/bluer-de7a250b8fd9af1c/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=service_class_uuids.json
  cargo:rerun-if-changed=bluetooth-numbers-database/v1/service_uuids.json

  --- stderr
  thread 'main' panicked at bluer/build.rs:256:6:
  services: Os { code: 2, kind: NotFound, message: "No such file or directory" }
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
     1: core::panicking::panic_fmt
               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
     2: core::result::unwrap_failed
               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
     3: core::result::Result<T,E>::expect
     4: build_script_build::build_ids
     5: build_script_build::main
     6: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I'm on Archlinux.

**Comment by surban** [comment]
Make sure to also check out all git submodules.
